### ISSUE TITLE
Can't resolve '@angular/platform-webworker/src/web_workers/shared/post_message_bus'

### ISSUE THREAD

**Issue by janvandenberg** [apoterenko/angular2-post-message#2]
Since we've upgraded to Angular 4.0.1 we get this error. I've tried to downgrade the @angular/platform-webworker to 4.0.0.rc-5 as in your example but I get the same error.

**Comment by janvandenberg** [comment]
Thanks for the quick response

**Comment by apoterenko** [comment]
Hi there.

Unfortunately, Angular does not export this API yet.

I am seeing into (4.0.1)

`node_modules/@angular/platform-webworker/@angular/platform-webworker.js`

and do not observe any opportunities for resolving this issue now. If we use webpack than this issue is iы not relevant

**Comment by janvandenberg** [comment]
@apoterenko how does webpack 'resolve' this issue?

**Comment by apoterenko** [comment]
via https://github.com/s-panferov/awesome-typescript-loader

**Comment by janvandenberg** [comment]
@apoterenko But the source files are not packages in @angular/platform/webworker

**Comment by apoterenko** [comment]
Oops, sorry. Yeah, they have removed sources *.js from a bundle since 4.0.x [god damn :(]. I thought that was another problem

**Comment by apoterenko** [comment]
I will try to copy the absent files as a temp workaround

**Comment by apoterenko** [comment]
Check out 1.2.1

**Comment by janvandenberg** [comment]
Thanks @apoterenko
