### ISSUE TITLE
Add remove listener 

### ISSUE THREAD

**Issue by realappie** [apoterenko/angular2-post-message#3]
Would be a great addition if we could clean remove listeners from bridges!

Something like

```this.brige.removeListener('bridgeName')```

**Comment by apoterenko** [comment]
Hi!

Check out 1.3.0:

`    /**
     * Remove a listener
     *
     * @param bridgeName Bridge name (aka Angular2 channel name)
     * @param listener Callback
     */
    removeListener(bridgeName: string, listener: Function): IPostMessageBridge;

    /**
     * Remove the all listeners
     *
     * @param bridgeName Bridge name (aka Angular2 channel name)
     */
    removeAllListeners(bridgeName: string): IPostMessageBridge;`
